apiVersion: v1
kind: Namespace
metadata:
  name: civa
  labels:
    app.kubernetes.io/part-of: civa
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: civa-monitoring
  labels:
    app.kubernetes.io/part-of: civa
